'''
Created on May 22, 2014

@author: Harsha

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


Answer:
4613732
'''

if __name__ == '__main__':
    fibn = 1
    fibn_1 = 1
    total = 0
    while fibn < 4000000 :
        temp = fibn
        fibn = fibn + fibn_1
        if fibn % 2 == 0 :
            total += fibn
        fibn_1 = temp
    print total
    
    '''
    alternate :
    Fib(n) = Fib(n-1) + Fib(n-2) = 4*Fib(n-3) + Fib(n-6)
    Every third number in series is even
    1 1 2 3 5 8 13 21 34 ...
    '''       
    fibn = 8
    fibn_3 = 2
    total = 10
    while True :
        temp = fibn
        fibn = 4 * fibn + fibn_3
        if fibn > 4000000 : break
        total += fibn
        fibn_3 = temp
    print total